### ISSUE TITLE
CLI support for all args

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#365]
Match gcloud CLI in providing CLI arguments for all options.

- [Android Run docs](https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run)
- [iOS Run Docs](https://cloud.google.com/sdk/gcloud/reference/alpha/firebase/test/ios/run)

### Android

- gcloudYml
  - [x] resultsBucket `--results-bucket=RESULTS_BUCKET` #413
  - [x] recordVideo `--record-video` `--no-record-video` #414
  - [x] timeout `--timeout=TIMEOUT` #415
  - [x] async `--async`#416
  - [x] project `--project=PROJECT` #417
  - [x] resultsHistoryName `--results-history-name=RESULTS_HISTORY_NAME` #418
- androidGcloudYml
  - [x] app `--app=APP` https://github.com/TestArmada/flank/pull/389
  - [x] test `--test=TEST` https://github.com/TestArmada/flank/pull/393
  - [x] autoGoogleLogin `--auto-google-login` `--no-auto-google-login` #405
  - [x] useOrchestrator `--use-orchestrator` `--no-use-orchestrator` https://github.com/TestArmada/flank/pull/395
  - [x] environmentVariables `--environment-variables=[KEY=VALUE,…]` #407
  - [x] directoriesToPull `--directories-to-pull=[DIR_TO_PULL,…]` #408
  - [x] performanceMetrics `--performance-metrics` `--no-performance-metrics` #406
  - [x] testTargets `--test-targets=TEST_TARGET,[TEST_TARGET,…]]` https://github.com/TestArmada/flank/pull/394
  - [x] device `--device=DIMENSION=VALUE,[…]` #409
- flankYml
  - [x] testShards `--test-shards=TEST_SHARDS` #419
  - [x] repeatTests `--repeat-tests=REPEAT_TESTS` #420
  - [x] testTargetsAlwaysRun `--test-targets-always-run=TEST_TARGET,[TEST_TARGET,…]]` #421
  - ? smartFlankGcsPath

### iOS

- gcloudYml
    - [x] resultsBucket `--results-bucket=RESULTS_BUCKET` #413
    - [x] recordVideo `--record-video` `--no-record-video` #414
    - [x] timeout `--timeout=TIMEOUT` #415
    - [x] async `--async` #416
    - [x] project `--project=PROJECT` #417
    - [x] resultsHistoryName `--results-history-name=RESULTS_HISTORY_NAME` #418
-  iosGcloudYml
    - [x] test `--test=XCTEST_ZIP` #423
    - [x] xctestrunFile `--xctestrun-file=XCTESTRUN_FILE`#424
    - [x] xcodeVersion `--xcode-version=XCODE_VERSION` #425
    - [x] device `--device=DIMENSION=VALUE,[…]` #426
- flankYml
    - [x] testShards `--test-shards=TEST_SHARDS` #419
    - [x] repeatTests `--repeat-tests=REPEAT_TESTS` #420
    - [x] testTargetsAlwaysRun `--test-targets-always-run=TEST_TARGET,[TEST_TARGET,…]]` #421
    - ? smartFlankGcsPath
-  iosFlankYml
   - [x] testTargets `--test-targets=TEST_TARGET,[TEST_TARGET,…]]` #422

# **All**
- [x] Fix help formatting #427
- [x] Check all params are listed (ex: Smart Flank)

Edge cases
- Test single value environment variable `clearPackageData `. Expected to be in KEY=VALUE format.

---

# Workflow for adding an Android only param:

AndroidRunCommand
  - doc from gcloud + nullable default

AndroidArgs.kt
  - cli.param ?: yaml.param

AndroidArgsTest.kt
  - minimal YAML, verify cli overrides yaml value

AndroidRunCommandTest.kt
  - empty_params_parse_null - update to verify default value is null
  - add param_parse test to verify command is parsed correctly.

# Workflow for adding an iOS param

IosRunCommand
  - Doc from gcloud + nullable default

IosArgs
  - cli?.param ?: yaml.param

IosArgsTest
  - Minimal YAML, verify cli overrides yaml value

IosRunCommandTest
  - empty_params_parse_null - update to verify default value is null
  - Add param_parse test to verify command is parsed correctly.

**Comment by Macarse** [comment]
@bootstraponline just fyi. I don't have permission to edit the checkboxes and/or add the PR number.

**Comment by bootstraponline** [comment]
I added you to the repo 🙂 you should have permission now
